### ISSUE TITLE
generating URL with IP instead of hostname

### ISSUE THREAD

**Issue by pluschris** [JohnHouwer/pypartypix#2]
Hi,
sometimes in my home network the hostname-resolution fails, but direct host access via IP works of course. Do we have any advantages generating the URL with the hostname? Otherwise I suggest using the ip.
Regards,
chris

**Comment by JohnHouwer** [comment]
Hi,
there are some advantages and some drawbacks, in python there is no reliable and per default  included interface to get all IPs from a host.
We could use [ifaddr](https://github.com/smurn/ifaddr) but it would add a dependency.

If we add a dependency we should make it optional.

Regards,
John

**Comment by JohnHouwer** [comment]
Hi, 
with the -H switch you can supply a custom hostname / IP.
Is this sufficient for your needs?

Regards,
John

**Comment by pluschris** [comment]
Hi,
it's fine with me.
Regards,
Chris
